src/app/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('shop.urls', namespace='shop'))
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/shop/urls.py
from django.urls import path
from .views import (
    products_view, 
    product_view, 
    product_add_view, 
    category_add_view,
    categories_view,
    category_edit_view,
    category_delete_view,
    product_edit_view,
    product_delete_view
    )

app_name = 'shop'

urlpatterns = [
    path('', products_view, name='products'),
    path('products/<int:pk>/',product_view, name='product'),
    path('products/add/', product_add_view, name='product_add'),
    path('categories/add/', category_add_view, name='category_add'),
    path('categories/', categories_view, name='categories'),
    path('categories/<int:pk>/edit/', category_edit_view, name='category_edit'),
    path('categories/<int:pk>/delete/', category_delete_view, name='category_delete'),
    path('products/<int:pk>/edit/', product_edit_view, name='product_edit'),
    path('products/<int:pk>/delete/', product_delete_view, name='product_delete')
]

src/shop/models.py
from distutils.command.upload import upload
from tkinter import CASCADE
from django.db import models
from ckeditor.fields import RichTextField

class Category(models.Model):
    name = models.CharField(null=False, blank=True, max_length=50)
    desc = RichTextField(null=True, blank=True)

    def __str__(self):
        return self.name

class Product(models.Model):
    name = models.CharField(null=False, blank=False, max_length=50)
    desc = RichTextField(null=True, blank=True)
    category = models.ForeignKey(to='Category', on_delete=models.CASCADE, blank=False, null=False, related_name='products')
    created_at = models.DateTimeField(auto_now_add=True)
    price = models.DecimalField(max_digits=15, decimal_places=2, default=0.00)
    image = models.ImageField(null=True, blank=True, upload_to='products/images/')

    @property
    def get_price(self):
        return f'{self.price}$'

    def __str__(self):
        return self.name

src/shop/forms.py
from dataclasses import fields
from django.forms import ModelForm
from .models import Product, Category
from django import forms

class ProductForm(ModelForm):
    class Meta:
        model = Product
        fields = ['name', 'desc', 'category', 'price', 'image']
        labels = {
            'name':'Название товара',
            'desc':'Описание товара',
            'category':'Категория',
            'price':'Цена',
            'image':'Изображение',
        }
        widgets = {
            'name':forms.TextInput(attrs={'class':'form-control name-input'}),
            'category':forms.Select(attrs={'class':'form-control category-input'}),
            'price':forms.TextInput(attrs={'class':'form-control price-input'}),
            'image':forms.FileInput(attrs={'class':'form-control image-input'}),
        }
    

class CategoryForm(ModelForm):
    class Meta:
        model = Category
        fields = ['name', 'desc']
        labels = {
            'name':'Название товара',
            'desc':'Описание товара',
        }
        widgets = {
            'name':forms.TextInput(attrs={'class':'form-control name-input'}),
        }

src/shop/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from .services import shop_services
from .forms import CategoryForm, ProductForm
from django.urls import reverse
# Create your views here.

def products_view(request):
    category_name = request.GET.get('category')
    if category_name:
        product_list = shop_services.get_product_list_by_category_name(category_name)
    else:
        product_list = shop_services.get_product_list()
    context = {
        'product_list': product_list
    }
    return render(request, 'shop/product_list.html', context)

def product_view(request, pk):
    product = shop_services.get_product_by_pk(pk=pk)
    context = {
        'product':product,
    }
    return render(request, 'shop/product_detail.html', context)

def product_add_view(request):
    form = ProductForm(request.POST or None, request.FILES or None)
    if form.is_valid():
        product = form.save()
        return redirect(reverse('shop:product', kwargs={'pk':product.id}))
    context = {
        'form': form,
    }
    return render(request, 'shop/product_create.html', context)

def category_add_view(request):
    form = CategoryForm(request.POST or None)
    if form.is_valid():
        category = form.save()
        return redirect('shop:products')
    context = {
        'form': form,
    }
    return render(request, 'shop/category_create.html', context)

def categories_view(request):
    category_list = shop_services.get_category_list()
    context = {
        'category_list': category_list,
    }
    return render(request, 'shop/category_list.html', context)

def category_edit_view(request, pk):
    category = shop_services.get_category_by_pk(pk)
    form = CategoryForm(request.POST or None, instance=category)
    if form.is_valid():
        form.save()
        return redirect('shop:categories')
    context={
        'form':form,
    }
    return render(request, 'shop/category_edit.html', context)

def category_delete_view(request, pk):
    category = shop_services.get_category_by_pk(pk)
    category.delete()
    return redirect('shop:categories')

def product_edit_view(request, pk):
    product = shop_services.get_product_by_pk(pk)
    form = ProductForm(request.POST or None,request.FILES or None, instance=product)
    if form.is_valid():
        form.save()
        return redirect(reverse('shop:product', kwargs={'pk': product.id}))
    context={
        'form':form,
    }
    return render(request, 'shop/product_edit.html', context)

def product_delete_view(request, pk):
    product = shop_services.get_product_by_pk(pk)
    product.delete()
    return redirect('shop:products')


    

src/shop/templates/shop/category_create.html
{% extends 'base.html' %}
{% block title %}
Добавление категории
{% endblock title %}

{% block content %}
<h2 class="mt-3">Создать категорию</h2>
<form action="" method="POST">
    {% csrf_token %}
    {{form.media }}
    {{ form.as_p }}
    <button class="btn btn-primary" type="submit">Создать</button>
</form>
{% endblock content%}

src/shop/templates/shop/category_edit.html
{% extends 'base.html' %}
{% block title %}
Редактирование категории
{% endblock title %}

{% block content %}
<h2 class="mt-3">Создать категорию</h2>
<form action="" method="POST">
    {% csrf_token %}
    {{form.media }}
    {{ form.as_p }}
    <button class="btn btn-primary" type="submit">Редактировать</button>
</form>
{% endblock content%}

src/shop/templates/shop/category_list.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
Категории
{% endblock title %}

{% block content %}
<h2 class="mt-3">Категории</h2>
<ul class="list-group mt-3">
    {% for category in category_list %}
    <li class="list-group-item d-flex justify-content-between" style="width:50%;">
        {{category.name}}
        <div class="d-flex gap-3">
            <a href="{% url 'shop:category_delete' category.pk %}"><img src="{% static 'shop/icons/trash.svg'%}"
                    alt=""></a>
            <a href="{% url 'shop:category_edit' category.pk %}"><img src="{% static 'shop/icons/pencil-square.svg'%}"
                    alt=""></a>
        </div>
    </li>
    {% endfor %}
</ul>
{% endblock content %}

src/shop/templates/shop/product_create.html
{% extends 'base.html' %}
{% block title %}
Добавление товара
{% endblock title %}

{% block content %}
<h2 class="mt-3">Создать категорию</h2>
<form action="" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{form.media }}
    {{ form.as_p }}
    <button class="btn btn-primary" type="submit">Создать</button>
</form>
{% endblock content%}

src/shop/templates/shop/product_detail.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
{{product.name}}
{% endblock title %}

{% block content %}
<h2 class="mt-3 text-center">{{product.name}}</h2>
<div class="card mb-3 mt-3 p-3 mx-auto" style="background-color:#FFFFFF;">
    <div class="row g-0">
        <div class="col-md-4 d-flex justify-content-center">
            <img src="{{product.image.url}}" class="img-fluid rounded-start" style="max-height:300px;" alt="...">
        </div>
        <div class="col-md-8">
            <div class="d-flex justify-content-end gap-3">
                <a href="{% url 'shop:product_delete' product.pk %}"><img src="{% static 'shop/icons/trash.svg'%}"
                        alt=""></a>
                <a href="{% url 'shop:product_edit' product.pk %}"><img src="{% static 'shop/icons/pencil-square.svg'%}"
                        alt=""></a>
            </div>
            <div class="card-body">
                <h5 class="card-title">{{product.name}}</h5>
                <p class="card-text"><small class="text-muted">Цена: </small>{{product.get_price}}</p>
                <p class="card-text"><small class="text-muted">Категория: </small> <a
                        href="{% url 'shop:products' %}?category={{product.category.name}}">{{product.category.name}}</a>
                </p>
                <p class="card-text">{{product.desc|safe}}</p>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

src/shop/templates/shop/product_edit.html
{% extends 'base.html' %}
{% block title %}
Редактировать товар
{% endblock title %}

{% block content %}
<h2 class="mt-3">Редактировать товар</h2>
<form action="" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{form.media }}
    {{ form.as_p }}
    <button class="btn btn-primary" type="submit">Применить</button>
</form>
{% endblock content%}

src/shop/templates/shop/product_list.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
Products
{% endblock title %}

{% block content %}
<h2 class="mt-3 text-center">Все товары</h2>
</h2>
<div class="row gx-2 gy-2 mt-3">
    {% for product in product_list %}
    <div class="col-sm-12 col-md-6">
        <div class="card mb-3" style="height:100%;">
            <div class="row g-0">
                <div class="col-md-6 d-flex justify-content-center">
                    <img src="{{product.image.url}}" class="img-fluid rounded-start p-3"
                        style="height: 100%; max-height: 200px;" alt="...">
                </div>
                <div class="col-md-6">
                    <div class="card-body">
                        <h5 class="card-title">{{product.name}}</h5>
                        <p class="card-text"><small class="text-muted">Категория: {{product.category.name}}</small></p>
                        <p>{{product.get_price}}</p>
                        <p><span>{{product.desc|safe|truncatewords_html:5}}</span></p>

                        <a href="{% url 'shop:product' product.pk %}">Подробнее</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
    {% endfor %}
</div>
{% endblock content %}

src/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %} {% endblock title %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'shop/css/style.css'%}">
</head>

<body>
    <header>
        <nav class="navbar navbar-expand-lg bg-danger">
            <div class="container">
                <a class="navbar-brand shop-logo" href="{% url 'shop:products' %}">Kaspi Shop</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
                    aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarNav">
                    <ul class="navbar-nav">
                        <li class="nav-item">
                            <a class="nav-link nav-link-custome" aria-current="page"
                                href="{% url 'shop:products' %}">Товары</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link nav-link-custome" aria-current="page"
                                href="{% url 'shop:categories' %}">Категории</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link nav-link-custome" href="{% url 'shop:product_add' %}">Добавить товар</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link nav-link-custome" href="{% url 'shop:category_add' %}">Добавить
                                категорию</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container mb-5">
        {% block content %}
        {% endblock content%}
    </div>
</body>

</html>